image: node:latest

cache:
  paths:
  - node_modules/

stages:
- build
- build_docker

compile:
  stage: build
  script:
  - npm install
  - mkdir build
  - npm run build
  tags:
  - docker
  artifacts:
    paths:
    - build/
    expire_in: 1 week

dockerize:
  stage: build_docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - mkdir -p /root/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - cd $CI_PROJECT_DIR
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
  - tags
  tags:
  - docker
